# version format
version: 1.0.2.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX will only be used for Release builds (alpha, beta, etc)
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
install:
  - cmd: npm install -g grunt-cli
  - cmd: set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=
  - cmd: set UMBRACO_PACKAGE_MIN_VERSION=7.1.4
  - cmd: cd BuildPackage
  - cmd: Build.bat

# to disable automatic builds
build: off

artifacts:
  - path: BuildPackage\Package\*.nupkg
  - path: BuildPackage\Package\*.zip

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/youtube-umbraco/
    api_key:
      secure: 2eRaWWs9xOh/21IoVhykZKWQEIrvWPcyPYr+J7yhxbmaylNHFY/NRjJxHmqMIMsv
    artifact: /.*\.nupkg/

  - provider: NuGet
    server: 
    api_key:
      secure: ouE7tpDB4dawEEQ0ig0uqq2dNEB7J6iDJ7smAPzhlKC/x/p23Txr5MRDqaIQzjYH
    artifact: /.*\.nupkg/
    on:
      branch: release

  - provider: S3
    access_key_id:
      secure: Zh199HrTKaRNia82d4PQWJPHseHptNlRApgijx2ejBQ=
    secret_access_key:
      secure: izFbvWxeneliuFrxwx4Eo7bSDhV9mHSueuBdOoo7blKIgkkY4HCkN1GQMbSU5Ae6
    bucket: umbraco-community-packages
    set_public: true
    folder: YouTube
    artifact: /.*\.zip/
